### ISSUE TITLE
How to record voice channel?

### ISSUE THREAD

**Issue by Kwabang** [sshh12/Recording-Bot#1]
How to record voice channel?
![image](https://user-images.githubusercontent.com/43908654/57573062-be992980-745d-11e9-94bd-987b99240ba8.png)

**Comment by MDeltaX** [comment]
Is this still open?

**Comment by sshh12** [comment]
Sorry @Kwabang I never got a notification for this issue until just now. By default the script records the channel audio (per speaker) in separate wav files. To access these files checkout the sample python scripts. 

```python
from recordingbot import Bot

class RepeatBot(Bot):

    def process(self, text, memberid, timestamp, wavefn):

        self.play(wavefn) # <- `wavefn` is an audio recording of the channel.

if __name__ == "__main__":

    bot = RepeatBot('voicedata', 'voiceapi.json')
    bot.run()
```
